### ISSUE TITLE
上传附件报错，疑似tika与poi冲突导致

### ISSUE THREAD

**Issue by Sunzhuokai** [o2oa/o2oa#139]
2023-01-13 13:18:48.416 [ApplicationServerQueuedThreadPool-44] INFO System.err - Caused by: java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES
2023-01-13 13:18:48.419 [ApplicationServerQueuedThreadPool-44] INFO System.err - 	at org.apache.tika.detect.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:212)
2023-01-13 13:18:48.422 [ApplicationServerQueuedThreadPool-44] INFO System.err - 	at org.apache.tika.detect.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:536)
2023-01-13 13:18:48.424 [ApplicationServerQueuedThreadPool-44] INFO System.err - 	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:85)
2023-01-13 13:18:48.425 [ApplicationServerQueuedThreadPool-44] INFO System.err - 	at org.apache.tika.Tika.detect(Tika.java:158)
2023-01-13 13:18:48.427 [ApplicationServerQueuedThreadPool-44] INFO System.err - 	at org.apache.tika.Tika.detect(Tika.java:185)
2023-01-13 13:18:48.428 [ApplicationServerQueuedThreadPool-44] INFO System.err - 	at org.apache.tika.Tika.detect(Tika.java:224)
2023-01-13 13:18:48.431 [ApplicationServerQueuedThreadPool-44] INFO System.err - 	at com.x.processplatform.assemble.surface.jaxrs.attachment.ActionUploadWithWork.execute(ActionUploadWithWork.java:69)
2023-01-13 13:18:48.434 [ApplicationServerQueuedThreadPool-44] INFO System.err - 	at com.x.processplatform.assemble.surface.jaxrs.attachment.AttachmentAction.upload(AttachmentAction.java:616)

**Comment by Sunzhuokai** [comment]
升级poi相关版本为5.1.0可解决

**Comment by qijian** [comment]
o2oa在最新版本V7.3.3解决了该问题，感谢支持
