### ISSUE TITLE
项目能不能拆下repo

### ISSUE THREAD

**Issue by walter211** [o2oa/o2oa#55]
哥，我知道你们屌，我clone的时候看着我2MB/S的速度度只有5%进度在缓慢移动的时候就哭了。

**Comment by o2oa** [comment]
Sorry，我们的仓库的确比较大，也考虑过拆库。因为我们希望保证用户下载源码后，可以直接编译打包成服务器，而不需要过多的操作，所以我们将5个JVM都放在仓库里了。请您理解。

**Comment by bigknife** [comment]
> Sorry，我们的仓库的确比较大，也考虑过拆库。因为我们希望保证用户下载源码后，可以直接编译打包成服务器，而不需要过多的操作，所以我们将5个JVM都放在仓库里了。请您理解。

macos 使用系统的jvm启动报错:
```java
Exception in thread "main" java.lang.NullPointerException
	at com.x.server.console.Main.loadJars(Main.java:804)
	at com.x.server.console.Main.main(Main.java:70)
```
