### ISSUE TITLE
jdk 11 启动项目有报错

### ISSUE THREAD

**Issue by cmdares** [o2oa/o2oa#63]
win10/jdk 11.0.5/o2server_20200107232400_windows
解压后直接启动，有如下异常，但是平台目前可以登陆使用。看异常的情况是跟调度有关，请官方适配jdk11的运行环境，感谢！
异常信息如下：
2020-01-08 22:16:29.549 INFO [DefaultQuartzScheduler_Worker-1] com.x.bbs.assemble.control.schedule.SubjectReplyTotalStatisticTask - Timertask[SubjectTotalStatisticTask] completed and excute success.
[DefaultQuartzScheduler_Worker-1] ERROR org.quartz.core.JobRunShell - Job com.x.base.core.project.x_query_service_processing.com.x.query.service.processing.schedule.CrawlWork threw an unhandled Exception: 
java.lang.Error: Unresolved compilation problems: 
	The method ids(Class<T>) in the type EntityManagerContainer is not applicable for the arguments (Class<Work>)
	Work cannot be resolved to a type

	at com.x.query.service.processing.schedule.CrawlWork.schedule(CrawlWork.java:54)
	at com.x.base.core.project.schedule.AbstractJob.execute(AbstractJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[DefaultQuartzScheduler_Worker-1] ERROR org.quartz.core.ErrorLogger - Job (com.x.base.core.project.x_query_service_processing.com.x.query.service.processing.schedule.CrawlWork threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.Error: Unresolved compilation problems: 
	The method ids(Class<T>) in the type EntityManagerContainer is not applicable for the arguments (Class<Work>)
	Work cannot be resolved to a type
]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.Error: Unresolved compilation problems: 
	The method ids(Class<T>) in the type EntityManagerContainer is not applicable for the arguments (Class<Work>)
	Work cannot be resolved to a type

	at com.x.query.service.processing.schedule.CrawlWork.schedule(CrawlWork.java:54)
	at com.x.base.core.project.schedule.AbstractJob.execute(AbstractJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
[DefaultQuartzScheduler_Worker-2] ERROR org.quartz.core.JobRunShell - Job com.x.base.core.project.x_query_service_processing.com.x.query.service.processing.schedule.CrawlWorkCompleted threw an unhandled Exception: 
java.lang.Error: Unresolved compilation problems: 
	The method ids(Class<T>) in the type EntityManagerContainer is not applicable for the arguments (Class<WorkCompleted>)
	WorkCompleted cannot be resolved to a type

	at com.x.query.service.processing.schedule.CrawlWorkCompleted.schedule(CrawlWorkCompleted.java:54)
	at com.x.base.core.project.schedule.AbstractJob.execute(AbstractJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
2020-01-08 22:16:29.784 INFO [DefaultQuartzScheduler_Worker-2] com.x.bbs.assemble.control.schedule.UserSubjectReplyPermissionStatisticTask - Timertask[UserSubjectReplyStatisticTask] completed and excute success.
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[DefaultQuartzScheduler_Worker-2] ERROR org.quartz.core.ErrorLogger - Job (com.x.base.core.project.x_query_service_processing.com.x.query.service.processing.schedule.CrawlWorkCompleted threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.Error: Unresolved compilation problems: 
	The method ids(Class<T>) in the type EntityManagerContainer is not applicable for the arguments (Class<WorkCompleted>)
	WorkCompleted cannot be resolved to a type
]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.Error: Unresolved compilation problems: 
	The method ids(Class<T>) in the type EntityManagerContainer is not applicable for the arguments (Class<WorkCompleted>)
	WorkCompleted cannot be resolved to a type

	at com.x.query.service.processing.schedule.CrawlWorkCompleted.schedule(CrawlWorkCompleted.java:54)
	at com.x.base.core.project.schedule.AbstractJob.execute(AbstractJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
2020-01-08 22:16:30.345 INFO [DefaultQuartzScheduler_Worker-2] com.x.attendance.assemble.control.schedule.MobileRecordAnalyseTask - Timertask MobileRecordAnalyseTask completed and excute success.
2020-01-08 22:16:30.866 INFO [DefaultQuartzScheduler_Worker-1] com.x.attendance.assemble.control.schedule.AttendanceStatisticTask - Timertask completed and excute success.
2020-01-08 22:16:31.866 INFO [DefaultQuartzScheduler_Worker-2] com.x.cms.assemble.control.timertask.Timertask_BatchOperationTask - Timertask_BatchOperationTask -> not fount any cms batch operation, try to check unreview document in database......
2020-01-08 22:16:31.909 INFO [DefaultQuartzScheduler_Worker-1] com.x.cms.assemble.control.timertask.Timertask_LogRecordCheckTask - Timertask_LogRecordCheckTask -> clean operation logs excute success. stay_yearnum:1,stay_count:100000
2020-01-08 22:16:32.073 INFO [DefaultQuartzScheduler_Worker-1] com.x.cms.assemble.control.timertask.Timertask_LogRecordCheckTask - Timertask_LogRecordCheckTask -> clean view records excute success. stay_yeanumr:1,stay_count:100000
java.lang.Exception: get entityManager for class com.x.cms.core.entity.Document error.
	at com.x.base.core.container.factory.EntityManagerContainerFactory.createEntityManager(EntityManagerContainerFactory.java:109)
	at com.x.base.core.container.EntityManagerContainerBasic.get(EntityManagerContainerBasic.java:35)
	at com.x.cms.assemble.control.factory.DocumentFactory.listUnReviewIds(DocumentFactory.java:396)
	at com.x.cms.assemble.control.service.DocumentInfoService.listUnReviewIds(DocumentInfoService.java:319)
	at com.x.cms.assemble.control.timertask.Timertask_BatchOperationTask.schedule(Timertask_BatchOperationTask.java:58)
	at com.x.base.core.project.schedule.AbstractJob.execute(AbstractJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: <openjpa-3.1.1-SNAPSHOT-rb27175b nonfatal general error> org.apache.openjpa.persistence.PersistenceException: Table "CMS_DOCUMENT" already exists; SQL statement:
CREATE TABLE CMS_DOCUMENT (xid VARCHAR(64) NOT NULL, xcreateTime TIMESTAMP, xscratchBoolean BOOLEAN, xscratchDate TIMESTAMP, xscratchInteger TIMESTAMP, xscratchString VARCHAR(255), xsequence VARCHAR(128), xupdateTime TIMESTAMP, xdistributeFactor INTEGER, xappAlias VARCHAR(96), xappId VARCHAR(64), xappName VARCHAR(96), xcategoryAlias VARCHAR(96), xcategoryId VARCHAR(64), xcategoryName VARCHAR(96), xcommendCount BIGINT, xcommentCount BIGINT, xcreatorIdentity VARCHAR(255), xcreatorPerson VARCHAR(255), xcreatorTopUnitName VARCHAR(255), xcreatorUnitName VARCHAR(255), xdescription VARCHAR(255), xdocStatus VARCHAR(16), xdocumentType VARCHAR(16), xform VARCHAR(64), xformName VARCHAR(96), xhasIndexPic BOOLEAN, ximportBatchName VARCHAR(128), xisTop BOOLEAN, xmodifyTime TIMESTAMP, xpublishTime TIMESTAMP, xreadFormId VARCHAR(64), xreadFormName VARCHAR(96), xreviewed BOOLEAN, xsequenceAppAlias VARCHAR(255), xsequenceCategoryAlias VARCHAR(255), xsequenceCreatorPerson VARCHAR(255), xsequenceCreatorUnitName VARCHAR(255), xsequenceTitle VARCHAR(255), xsummary VARCHAR(255), xtitle VARCHAR(255), xviewCount BIGINT, PRIMARY KEY (xid), CONSTRAINT CMS_DOCUMENT_DUC UNIQUE (xid, xcreateTime, xupdateTime, xsequence)) [42101-200] {stmnt 1729711293 CREATE TABLE CMS_DOCUMENT (xid VARCHAR(64) NOT NULL, xcreateTime TIMESTAMP, xscratchBoolean BOOLEAN, xscratchDate TIMESTAMP, xscratchInteger TIMESTAMP, xscratchString VARCHAR(255), xsequence VARCHAR(128), xupdateTime TIMESTAMP, xdistributeFactor INTEGER, xappAlias VARCHAR(96), xappId VARCHAR(64), xappName VARCHAR(96), xcategoryAlias VARCHAR(96), xcategoryId VARCHAR(64), xcategoryName VARCHAR(96), xcommendCount BIGINT, xcommentCount BIGINT, xcreatorIdentity VARCHAR(255), xcreatorPerson VARCHAR(255), xcreatorTopUnitName VARCHAR(255), xcreatorUnitName VARCHAR(255), xdescription VARCHAR(255), xdocStatus VARCHAR(16), xdocumentType VARCHAR(16), xform VARCHAR(64), xformName VARCHAR(96), xhasIndexPic BOOLEAN, ximportBatchName VARCHAR(128), xisTop BOOLEAN, xmodifyTime TIMESTAMP, xpublishTime TIMESTAMP, xreadFormId VARCHAR(64), xreadFormName VARCHAR(96), xreviewed BOOLEAN, xsequenceAppAlias VARCHAR(255), xsequenceCategoryAlias VARCHAR(255), xsequenceCreatorPerson VARCHAR(255), xsequenceCreatorUnitName VARCHAR(255), xsequenceTitle VARCHAR(255), xsummary VARCHAR(255), xtitle VARCHAR(255), xviewCount BIGINT, PRIMARY KEY (xid), CONSTRAINT CMS_DOCUMENT_DUC UNIQUE (xid, xcreateTime, xupdateTime, xsequence))} [code=42101, state=42S01]
	at org.apache.openjpa.jdbc.meta.MappingTool.record(MappingTool.java:625)
	at org.apache.openjpa.jdbc.meta.MappingTool.record(MappingTool.java:489)
	at org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory.synchronizeMappings(JDBCBrokerFactory.java:177)
	at org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory.synchronizeMappings(JDBCBrokerFactory.java:181)
	at org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory.newBrokerImpl(JDBCBrokerFactory.java:138)
	at org.apache.openjpa.kernel.AbstractBrokerFactory.newBroker(AbstractBrokerFactory.java:213)
	at org.apache.openjpa.kernel.DelegatingBrokerFactory.newBroker(DelegatingBrokerFactory.java:166)
	at org.apache.openjpa.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:262)
	at org.apache.openjpa.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:177)
	at org.apache.openjpa.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:167)
	at org.apache.openjpa.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:64)
	at com.x.base.core.container.factory.EntityManagerContainerFactory.createEntityManager(EntityManagerContainerFactory.java:103)
	... 7 more
Caused by: org.apache.openjpa.lib.jdbc.ReportingSQLException: Table "CMS_DOCUMENT" already exists; SQL statement:
CREATE TABLE CMS_DOCUMENT (xid VARCHAR(64) NOT NULL, xcreateTime TIMESTAMP, xscratchBoolean BOOLEAN, xscratchDate TIMESTAMP, xscratchInteger TIMESTAMP, xscratchString VARCHAR(255), xsequence VARCHAR(128), xupdateTime TIMESTAMP, xdistributeFactor INTEGER, xappAlias VARCHAR(96), xappId VARCHAR(64), xappName VARCHAR(96), xcategoryAlias VARCHAR(96), xcategoryId VARCHAR(64), xcategoryName VARCHAR(96), xcommendCount BIGINT, xcommentCount BIGINT, xcreatorIdentity VARCHAR(255), xcreatorPerson VARCHAR(255), xcreatorTopUnitName VARCHAR(255), xcreatorUnitName VARCHAR(255), xdescription VARCHAR(255), xdocStatus VARCHAR(16), xdocumentType VARCHAR(16), xform VARCHAR(64), xformName VARCHAR(96), xhasIndexPic BOOLEAN, ximportBatchName VARCHAR(128), xisTop BOOLEAN, xmodifyTime TIMESTAMP, xpublishTime TIMESTAMP, xreadFormId VARCHAR(64), xreadFormName VARCHAR(96), xreviewed BOOLEAN, xsequenceAppAlias VARCHAR(255), xsequenceCategoryAlias VARCHAR(255), xsequenceCreatorPerson VARCHAR(255), xsequenceCreatorUnitName VARCHAR(255), xsequenceTitle VARCHAR(255), xsummary VARCHAR(255), xtitle VARCHAR(255), xviewCount BIGINT, PRIMARY KEY (xid), CONSTRAINT CMS_DOCUMENT_DUC UNIQUE (xid, xcreateTime, xupdateTime, xsequence)) [42101-200] {stmnt 1729711293 CREATE TABLE CMS_DOCUMENT (xid VARCHAR(64) NOT NULL, xcreateTime TIMESTAMP, xscratchBoolean BOOLEAN, xscratchDate TIMESTAMP, xscratchInteger TIMESTAMP, xscratchString VARCHAR(255), xsequence VARCHAR(128), xupdateTime TIMESTAMP, xdistributeFactor INTEGER, xappAlias VARCHAR(96), xappId VARCHAR(64), xappName VARCHAR(96), xcategoryAlias VARCHAR(96), xcategoryId VARCHAR(64), xcategoryName VARCHAR(96), xcommendCount BIGINT, xcommentCount BIGINT, xcreatorIdentity VARCHAR(255), xcreatorPerson VARCHAR(255), xcreatorTopUnitName VARCHAR(255), xcreatorUnitName VARCHAR(255), xdescription VARCHAR(255), xdocStatus VARCHAR(16), xdocumentType VARCHAR(16), xform VARCHAR(64), xformName VARCHAR(96), xhasIndexPic BOOLEAN, ximportBatchName VARCHAR(128), xisTop BOOLEAN, xmodifyTime TIMESTAMP, xpublishTime TIMESTAMP, xreadFormId VARCHAR(64), xreadFormName VARCHAR(96), xreviewed BOOLEAN, xsequenceAppAlias VARCHAR(255), xsequenceCategoryAlias VARCHAR(255), xsequenceCreatorPerson VARCHAR(255), xsequenceCreatorUnitName VARCHAR(255), xsequenceTitle VARCHAR(255), xsummary VARCHAR(255), xtitle VARCHAR(255), xviewCount BIGINT, PRIMARY KEY (xid), CONSTRAINT CMS_DOCUMENT_DUC UNIQUE (xid, xcreateTime, xupdateTime, xsequence))} [code=42101, state=42S01]
	at org.apache.openjpa.lib.jdbc.LoggingConnectionDecorator.wrap(LoggingConnectionDecorator.java:219)
	at org.apache.openjpa.lib.jdbc.LoggingConnectionDecorator.wrap(LoggingConnectionDecorator.java:203)
	at org.apache.openjpa.lib.jdbc.LoggingConnectionDecorator.access$700(LoggingConnectionDecorator.java:58)
	at org.apache.openjpa.lib.jdbc.LoggingConnectionDecorator$LoggingConnection$LoggingStatement.executeUpdate(LoggingConnectionDecorator.java:955)
	at org.apache.openjpa.lib.jdbc.DelegatingStatement.executeUpdate(DelegatingStatement.java:123)
	at org.apache.openjpa.jdbc.schema.SchemaTool.executeSQL(SchemaTool.java:1377)
	at org.apache.openjpa.jdbc.schema.SchemaTool.createTable(SchemaTool.java:1117)
	at org.apache.openjpa.jdbc.schema.SchemaTool.buildSchema(SchemaTool.java:659)
	at org.apache.openjpa.jdbc.schema.SchemaTool.add(SchemaTool.java:562)
	at org.apache.openjpa.jdbc.schema.SchemaTool.add(SchemaTool.java:401)
	at org.apache.openjpa.jdbc.schema.SchemaTool.run(SchemaTool.java:373)
	at org.apache.openjpa.jdbc.meta.MappingTool.record(MappingTool.java:571)
	... 18 more
2020-01-08 22:16:32.317 INFO [DefaultQuartzScheduler_Worker-2] com.x.cms.assemble.control.timertask.Timertask_BatchOperationTask - Timertask_BatchOperationTask -> batch operations timer task excute completed.
2020-01-08 22:16:32.412 PRINT [DefaultQuartzScheduler_Worker-1] com.x.query.service.processing.schedule.CrawlCms - 内容管理索引器条目总数:0, 内容总数:0, 需要新增:0, 需要删除:0, 更新数量:0, 数量限制:1000, 耗时2532ms.
[DefaultQuartzScheduler_Worker-1] ERROR org.quartz.core.JobRunShell - Job com.x.base.core.project.x_processplatform_assemble_bam.com.x.processplatform.assemble.bam.schedule.PeriodTimer threw an unhandled Exception: 
java.lang.Error: Unresolved compilation problems: 
	The method get(Class<T>) in the type EntityManagerContainerBasic is not applicable for the arguments (Class<Task>)
	Task cannot be resolved to a type
	Task cannot be resolved to a type
	The method from(Class<Task>) from the type AbstractQuery<String> refers to the missing type Task
	Task cannot be resolved to a type
	SingularAttribute<Task,Date> cannot be resolved to a type
	SingularAttribute<Task,String> cannot be resolved to a type

	at com.x.processplatform.assemble.bam.jaxrs.period.TimerStartTaskApplicationStubs.listApplicationFromTask(TimerStartTaskApplicationStubs.java:60)
	at com.x.processplatform.assemble.bam.jaxrs.period.TimerStartTaskApplicationStubs.execute(TimerStartTaskApplicationStubs.java:39)
	at com.x.processplatform.assemble.bam.schedule.PeriodTimer.schedule(PeriodTimer.java:33)
	at com.x.base.core.project.schedule.AbstractJob.execute(AbstractJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[DefaultQuartzScheduler_Worker-1] ERROR org.quartz.core.ErrorLogger - Job (com.x.base.core.project.x_processplatform_assemble_bam.com.x.processplatform.assemble.bam.schedule.PeriodTimer threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.Error: Unresolved compilation problems: 
	The method get(Class<T>) in the type EntityManagerContainerBasic is not applicable for the arguments (Class<Task>)
	Task cannot be resolved to a type
	Task cannot be resolved to a type
	The method from(Class<Task>) from the type AbstractQuery<String> refers to the missing type Task
	Task cannot be resolved to a type
	SingularAttribute<Task,Date> cannot be resolved to a type
	SingularAttribute<Task,String> cannot be resolved to a type
]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.Error: Unresolved compilation problems: 
	The method get(Class<T>) in the type EntityManagerContainerBasic is not applicable for the arguments (Class<Task>)
	Task cannot be resolved to a type
	Task cannot be resolved to a type
	The method from(Class<Task>) from the type AbstractQuery<String> refers to the missing type Task
	Task cannot be resolved to a type
	SingularAttribute<Task,Date> cannot be resolved to a type
	SingularAttribute<Task,String> cannot be resolved to a type

	at com.x.processplatform.assemble.bam.jaxrs.period.TimerStartTaskApplicationStubs.listApplicationFromTask(TimerStartTaskApplicationStubs.java:60)
	at com.x.processplatform.assemble.bam.jaxrs.period.TimerStartTaskApplicationStubs.execute(TimerStartTaskApplicationStubs.java:39)
	at com.x.processplatform.assemble.bam.schedule.PeriodTimer.schedule(PeriodTimer.java:33)
	at com.x.base.core.project.schedule.AbstractJob.execute(AbstractJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
[DefaultQuartzScheduler_Worker-2] ERROR org.quartz.core.JobRunShell - Job com.x.base.core.project.x_processplatform_assemble_bam.com.x.processplatform.assemble.bam.schedule.StateTimer threw an unhandled Exception: 
java.lang.Error: Unresolved compilation problems: 
	The method get(Class<T>) in the type EntityManagerContainerBasic is not applicable for the arguments (Class<Application>)
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	The method createQuery(Class<Application>) from the type CriteriaBuilder refers to the missing type Application
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	Application cannot be resolved to a type

	at com.x.processplatform.assemble.bam.jaxrs.state.TimerApplicationStubs.execute(TimerApplicationStubs.java:44)
	at com.x.processplatform.assemble.bam.schedule.StateTimer.schedule(StateTimer.java:30)
	at com.x.base.core.project.schedule.AbstractJob.execute(AbstractJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[DefaultQuartzScheduler_Worker-2] ERROR org.quartz.core.ErrorLogger - Job (com.x.base.core.project.x_processplatform_assemble_bam.com.x.processplatform.assemble.bam.schedule.StateTimer threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.Error: Unresolved compilation problems: 
	The method get(Class<T>) in the type EntityManagerContainerBasic is not applicable for the arguments (Class<Application>)
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	The method createQuery(Class<Application>) from the type CriteriaBuilder refers to the missing type Application
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	Application cannot be resolved to a type
]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.Error: Unresolved compilation problems: 
	The method get(Class<T>) in the type EntityManagerContainerBasic is not applicable for the arguments (Class<Application>)
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	The method createQuery(Class<Application>) from the type CriteriaBuilder refers to the missing type Application
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	Application cannot be resolved to a type
	Application cannot be resolved to a type

	at com.x.processplatform.assemble.bam.jaxrs.state.TimerApplicationStubs.execute(TimerApplicationStubs.java:44)
	at com.x.processplatform.assemble.bam.schedule.StateTimer.schedule(StateTimer.java:30)
	at com.x.base.core.project.schedule.AbstractJob.execute(AbstractJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more

**Comment by o2oa** [comment]
O2OA支持JDK8，JDK11我们的确没有进行过严格测试.
