### ISSUE TITLE
编译通过之后无法启动

### ISSUE THREAD

**Issue by yzn-97** [o2oa/o2oa#89]
C:\Users\37656\Desktop\o2oa-O2OA-master\O2OA\target\o2server>"C:\Users\37656\Desktop\o2oa-O2OA-master\O2OA\target\o2server\jvm\windows\bin\java" -javaagent:"C:\Users\37656\Desktop\o2oa-O2OA-master\O2OA\target\o2server\console.jar" -server -Xms2g -Xmx4g -Duser.timezone=GMT+08 -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -jar "C:\Users\37656\Desktop\o2oa-O2OA-master\O2OA\target\o2server\console.jar"
java.io.IOException: invalid directory: commons/ext
        at com.x.server.console.InstrumentationAgent.loadWithCfg(InstrumentationAgent.java:73)
        at com.x.server.console.InstrumentationAgent.premain(InstrumentationAgent.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at com.x.server.console.Main.cleanTempDir(Main.java:592)
        at com.x.server.console.Main.init(Main.java:109)
        at com.x.server.console.Main.main(Main.java:119)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 3 more

咋整

**Comment by zhouruicn** [comment]
需要导入commons目录才可以进行编译打包.在平台说明页面有说明如何下载.
http://www.o2oa.net/course/ng5iqb.html 外部依赖目录下载
